Algoritmo "raio_udemy"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/06/2022
Var
  raio , area : real



Inicio
      Escreval("Digite o valor do raio do circulo:")
      Leia(raio)
      area <- 3.14*(raio*raio)
      Escreval("AREA=",area )

Fimalgoritmo