Algoritmo "senha_fixa_udemy"
// Disciplina   : [Linguagem e Lógica de Programação]
// Autor(a)    : José Edson Noé.
// Data atual  : 13/06/2022
Var
   senha : inteiro

Inicio
      Escreva("Digite a senha:")
      Leia(senha)
      
      Enquanto senha <> 2002 Faca
               Escreva("Senha Invalida! Tente novamente:")
               Leia(senha)
      FimEnquanto
      
      Escreva("Acesso permitido!")

Fimalgoritmo